'use strict';
// In-app navigation history; never sends the learner to an unrelated browser page.
const navigationHistory=[];
let currentRoute=null,restoringRoute=false;
function trackedPage(name,fn){return function(...args){if(!restoringRoute){const key=JSON.stringify([name,args]);if(currentRoute&&currentRoute.key!==key){if(!(name==='search'&&currentRoute.name==='search')){currentRoute.scroll=window.scrollY;currentRoute.search=$('#search').value;navigationHistory.push(currentRoute);if(navigationHistory.length>100)navigationHistory.shift();}}currentRoute={name,args,key,scroll:0,search:$('#search').value};}return fn(...args);};}
async function returnToPrevious(){if($('#modal').open){$('#modal').close();return;}if(!course||!state)return;const button=$('#goBack');button.disabled=true;try{if(dirty){await persist();if(dirty){toast('笔记尚未保存，已留在当前页；请先导出备份。');return;}}const target=navigationHistory.pop()||{name:'home',args:[],key:'["home",[]]',scroll:0,search:''};restoringRoute=true;currentRoute=target;$('#search').value=target.search||'';await navigationRoutes[target.name](...target.args);window.scrollTo(0,target.scroll||0);}finally{restoringRoute=false;button.disabled=false;}}
// Concept visuals are teaching examples, never measured restoration results.
const CONCEPT_VISUALS={
convolution:{title:'卷积核像一个滑动的小窗口',plain:'拿一张只露出3×3格子的纸板在图上移动，每停一次，把窗口内的信息汇成一个数。每个输出对应一个局部窗口。',meaning:'输入5×5，单通道，3×3核的权重全为1，步幅1，无补边、无偏置；输出3×3，每格是对应窗口九个数的和。',limit:'真实卷积核权重由训练学习，且常有多通道；这里不是平均池化，也没有展示完整卷积网络。',label:'输出格子编号（逐行，从0开始）',min:0,max:8,step:1,value:0,ask:'为什么输出不是5×5？',answer:'3格窗口在5格宽度上只能无补边地放3个位置，所以每边是5−3+1=3。'},
cost:{title:'省下采样时间，还要扣掉决策开销',plain:'换一条更短的路，如果找路花的时间超过省下的时间，总行程反而更长。算法加速也要算总账。',meaning:'旧方案采样100ms、其他10ms；新方案采样60ms、其他10ms，再加滑块指定的决策开销。比较相同端到端口径。',limit:'所有时间都是教学设定，不能当作本机GPU实测。真实评测还要统一预热、同步、精度和分辨率。',label:'新增决策开销（ms）',min:0,max:80,step:5,value:10,ask:'决策开销40ms时还有加速吗？',answer:'没有；新总延迟60+10+40=110ms，正好等于旧方案。'},
environment:{title:'程序究竟在哪里运行？',plain:'把脚本想成菜谱，Python解释器是厨师，Conda环境是厨师能用的工具箱。换目录只是拿到另一份菜谱，不会自动换厨师。',meaning:'先确认解释器，再运行.py脚本，最后检查输出；这三个对象不是同一个东西。',limit:'这是执行关系图，不会替你切换环境或运行终端命令。',label:'查看执行阶段',min:0,max:2,step:1,value:0,ask:'为什么cd到项目目录不等于激活Conda环境？',answer:'cd只改当前目录，conda activate才改变所用解释器和包的查找环境。'},
matrix:{title:'点积就是“配对相乘，再汇总”',plain:'两种材料分别买多少、各自单价多少？对应相乘再相加，就是一次点积。矩阵乘向量只是对每一行重复这件事。',meaning:'矩阵A有2行2列，向量x=[1,2]；每一行与x做点积，得到输出向量中的一个数。',limit:'例子表示线性组合，不把一般矩阵乘法理解为对应位置直接相乘。',label:'选择矩阵的行',min:0,max:1,step:1,value:0,ask:'为什么结果有两个数？',answer:'A有两行；每行汇总得到一个输出分量。'},
tensor:{title:'换轴，不是把像素打乱',plain:'同一批照片可以先按照片分，再按颜色分。改变整理顺序不应该改变某个像素原来的值。',meaning:'这里H=2、W=3、C=3。HWC与CHW代表索引顺序；滑块选择同一个颜色通道，对应像素数值相同。',limit:'这里只画一个通道的二维切片；真实BCHW还多一个批量B维。reshape不能随意代替permute。',label:'通道编号 C',min:0,max:2,step:1,value:0,ask:'HWC[0,1,2]在CHW中应写什么？',answer:'CHW[2,0,1]；只是把通道索引移到前面。'},
spread:{title:'均值相同，不等于一样分散',plain:'两组同学平均身高相同，一组很接近，一组差别很大。均值描述中心，标准差描述离中心有多散。',meaning:'图中三个数为[2−s,2,2+s]，s是滑块间距；总体方差=2s²/3，标准差是其平方根。',limit:'三个点的离散例子不是高斯分布；总体方差的分母是3，不是样本无偏方差的分母2。',label:'离中心的间距 s',min:0,max:2,step:.1,value:1,ask:'整体加10，方差会变吗？',answer:'不会。中心也加10，每个数减去中心的差不变。'},
gradient:{title:'沿坡下山，步子太大也会翻过去',plain:'梯度像坡度指示，告诉你往哪个方向上升。要减小损失就朝反方向走，但走太远可能比起点还高。',meaning:'示例L=(w−1)²，起点w=2，梯度为2；更新w′=2−2η。滑块η是学习率，不是梯度。',limit:'一维光滑曲线便于理解；真实网络不是只有一个参数，也不保证每一步都下降。',label:'学习率 η',min:0,max:1.5,step:.05,value:.25,ask:'η=1.5时为什么比起点差？',answer:'w′=−1，损失4大于起点损失1。方向没错，但步子过大。'},
training:{title:'训练是一圈，推理只走前半段',plain:'做题、对答案、找错因、调整方法，再做下一题。训练也是这样的反馈循环；推理时不能偷看正确答案再更新。',meaning:'输入→预测→损失→梯度→参数更新。训练标签用于计算损失；部署推理通常只有输入与训练好的模型。',limit:'本图是普通监督训练闭环；扩散训练的标签常是当次加入的噪声。',label:'查看训练阶段',min:0,max:4,step:1,value:0,ask:'eval()是否自动关闭梯度记录？',answer:'不是。eval切换模型行为，inference_mode或no_grad负责关闭梯度追踪。'},
noise:{title:'加噪是两种成分按系数混合',plain:'像把清晰信号逐渐掺入沙沙声。滑动时始终用同一份噪声，才看得出系数变化本身的影响。',meaning:'xₜ=√ᾱ·x₀+√(1−ᾱ)·ε。ᾱ控制信号保留量；系数要开平方。实线是混合结果，虚线是原信号。',limit:'这是一维信号演示，ε为固定种子高斯样本；不代表训练出的图像恢复效果。',label:'累计信号保留量 ᾱ',min:0,max:1,step:.01,value:.64,ask:'ᾱ=0与1分别得到什么？',answer:'0时只剩噪声ε；1时只剩原信号x₀。'},
schedule:{title:'累计保留量是连乘，不是相加',plain:'每次保留80%，第二次是在上一次剩余部分上再保留80%，两次后只有64%。',meaning:'这里每一步α=0.8，经过t步的ᾱₜ=0.8ᵗ。横轴是离散步数，纵轴是累计保留比例。',limit:'恒定α只为手算方便，真实训练常用随时间变化的日程，推理还需匹配训练约定。',label:'累计步数 t',min:1,max:10,step:1,value:3,ask:'3步后为什么不是2.4？',answer:'0.8×0.8×0.8=0.512；保留比例不能通过相加累计。'},
ode:{title:'小步沿斜率走，逼近连续曲线',plain:'导航只在少量路口更新方向，路线可能偏离；更新得更频繁通常更贴近路线，但要多付计算成本。',meaning:'dx/dt=−x，x(0)=1，精确解为e⁻ᵗ。Euler每步x←x+h(−x)，h=1/n。',limit:'这里的误差是数值积分误差，不等于图像恢复误差；更多步也不能修复错误模型。',label:'Euler完整步数 n',min:1,max:16,step:1,value:4,ask:'Heun做同样n步，函数调用也为n吗？',answer:'通常是2n；比较求解器需统一函数评估预算，而不只统一步数。'},
metric:{title:'PSNR把像素误差换成对数刻度',plain:'误差缩小10倍，PSNR增加10分贝。它方便比较数值，但不能告诉你细节是不是编出来的。',meaning:'动态范围L=1，PSNR=−10 log₁₀(MSE)。MSE是平均平方误差；滑块显示其十进制负指数k。',limit:'只有正确配对和一致评测协议才可比较；PSNR不等于感知质量或真实细节保证。',label:'MSE=10⁻ᵏ 中的 k',min:1,max:5,step:.1,value:2,ask:'MSE=0时PSNR是多少？',answer:'正无穷，需要单独处理，不能填写成0。'},
posterior:{title:'先验与观测，谁更可靠就更靠近谁',plain:'以前的经验与这一次测量发生冲突时，你会更相信噪声小的一方。高斯后验把这件事写成加权平均。',meaning:'先验均值μ=0.5、标准差τ=0.25，观测y=0.7；改变观测噪声标准差σ，后验均值m会在二者之间移动。',limit:'这是先验和噪声都为高斯时的解析例子；后验方差不是恢复达标概率。',label:'观测噪声标准差 σ',min:.05,max:1,step:.05,value:.25,ask:'σ越来越大时，后验均值靠近谁？',answer:'观测更不可信，因此趋向先验均值0.5。'},
budget:{title:'先筛选可靠候选，再比较真实成本',plain:'像选择快递：先排除你不放心的方案，再从剩下的选成本低者。没有放心方案，就用验证过的默认方案。',meaning:'候选8/16/32步的教学达标概率为0.70/0.92/0.96，教学成本12/21/40ms。每档独立达标，不是互斥分类。',limit:'概率和成本都是假设；阈值0.95不保证错误率≤5%。默认16步是教学设定，不能机械取最大步数。',label:'达标概率门槛',min:.5,max:.99,step:.01,value:.9,ask:'没有候选达标时为何仍选16步？',answer:'它是预先验证的默认方案；这是回退，不是声称其预测概率满足当前门槛。'},
calibration:{title:'说“九成把握”，真的十次对九次吗？',plain:'一个人每次都很自信，不等于判断可靠。校准检查很多相似置信度的预测，在实际中有多大比例成功。',meaning:'这个分箱中每个样本都预测0.9，共10个样本；滑块改变真正达标个数。虚线为预测0.9，实心柱为实际比例。',limit:'一个小分箱不能证明整体或跨域校准，更不能保证最终被选中的低预算样本错误率。',label:'10个样本中的达标数',min:0,max:10,step:1,value:7,ask:'7/10达标时可以直接说“校准误差就是0.2”吗？',answer:'这个分箱的经验差为0.2；整体校准还需更多分箱、样本及不确定性分析。'},
split:{title:'先按场景分开，再做裁剪',plain:'同一张照片裁成两块，一块拿去练习、一块拿来考试，仍可能泄题。文件不同不代表场景独立。',meaning:'每个字母代表一个原始场景，后缀1/2代表该场景的裁剪。按钮展示正确与有泄漏风险的分组。',limit:'真实数据还需检查连拍、同一对象、数据版本与近重复；这只是最小例子。',label:'拆分方式：0按场景，1混合裁剪',min:0,max:1,step:1,value:0,ask:'为什么固定seed不能解决场景泄漏？',answer:'seed让错误拆分可重复，却不能让同源图像变成独立场景。'},
local:{title:'平均亮度相同，局部困难可以不同',plain:'平均气温相同的两个城市，可能一个昼夜差很大，一个全天温和。只看平均值会丢失这种结构。',meaning:'四个区域亮度为[0.5−d,0.5+d,0.5−d,0.5+d]；整体均值始终0.5，局部方差为d²。',limit:'局部差异可见不等于它能预测预算；仍需全局/局部匹配参数量的实验。',label:'局部亮度差 d',min:0,max:.45,step:.05,value:.3,ask:'为什么不先把每个区域都独立标准化？',answer:'这可能抹掉亮度与对比度差异，而这些可能正是要预测的退化信号。'},
nullspace:{title:'观测看不见的部分，可以错得很离谱',plain:'只测量一个人的身高，不能知道他的体重。符合已观察信息，不代表没观察到的部分也正确。',meaning:'A=[1,0]只取第一个分量，y=1。候选x̂=[1,z]对任意z都有A x̂=1；以[1,0]为参考，平方误差为z²。',limit:'线性零空间反例说明一致性不足以证明恢复正确，不是说一致性完全没有用途。',label:'不可观测的第二分量 z',min:0,max:10,step:.5,value:3,ask:'残差始终0，恢复误差为什么在增加？',answer:'残差只检查第一个分量；第二个分量变化被A完全忽略。'},
risk:{title:'同样的错误数，换分母就是另一个问题',plain:'100张图里60张加速，其中6张失败。对全部图像是6%，对接受加速的图像却是10%。',meaning:'固定总数100、加速数60；改变错误数f。覆盖率=60/100，全体错误比例=f/100，选择后失败率=f/60。',limit:'错误必须由预先冻结的质量标准判定；没有加速样本时选择后失败率不适用。',label:'60张加速图中的失败数 f',min:0,max:60,step:1,value:6,ask:'低全体错误比例一定表示加速决策可靠吗？',answer:'不一定。覆盖率很低也能让全体错误比例变小，需同时报告选择后失败率和覆盖率。'},
uncertainty:{title:'样本越多，均值通常越稳定',plain:'只问几个人得到的平均意见容易波动；问更多独立的人，平均值通常更稳定，但偏差不会自动消失。',meaning:'固定标准差SD=2，标准误SE=2/√N。图中条带只表示均值±1SE，不是95%置信区间。',limit:'N必须是独立场景数量。同一场景的多个随机种子不能直接当成多个独立场景。',label:'独立场景数 N',min:4,max:100,step:4,value:16,ask:'样本数翻4倍，SE变多少？',answer:'变为一半，因为分母是样本数的平方根。'},
};
const VISUAL_LESSONS={environment:['b1','w1d1'],matrix:['b4'],tensor:['w1d3','w1d7'],spread:['b5'],gradient:['b7','b8','w1d4'],training:['w1d5','w2d3'],noise:['w2d1','w2d4'],schedule:['w2d2','w2d5','w2d7'],ode:['w3d1','w3d2','w3d4'],metric:['w4d3','w4d4','w4d5'],posterior:['w5d1','w5d2','w5d3','w5d4'],budget:['w5d6','w6d1','w6d2','w6d5','w6d6'],calibration:['w6d3','w6d4'],split:['w4d6'],local:['w7d1','w7d2','w7d6'],nullspace:['w7d3','w7d4'],risk:['b6','w7d5','w7d7'],uncertainty:['w8d2','w8d3']};

// All SVG geometry is calculated from the current teaching parameters.
Object.assign(VISUAL_LESSONS,{convolution:['w1d6'],cost:['w3d5','w3d6']});
function conceptDrawing(kind,v){
 const tx=(x,y,t)=>`<text x="${x}" y="${y}" text-anchor="middle">${esc(t)}</text>`;
 const line=(x1,y1,x2,y2,c='v-axis')=>`<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" class="${c}"/>`;
 const dot=(x,y)=>`<circle cx="${x}" cy="${y}" r="5" fill="var(--series)"/>`;
 const box=(x,y,w,h,t)=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="5" class="v-node"/>${tx(x+w/2,y+h/2+5,t)}`;
 const path=(points,c='v-line')=>`<polyline points="${points.map(p=>p.join(',')).join(' ')}" class="${c}"/>`;
 const axis=()=>line(38,185,300,185)+line(38,185,38,28);
 let svg='',out='',legend=false;
 if(kind==='convolution'){const row=Math.floor(v/3),col=v%3;svg=tx(82,25,'输入5×5')+tx(252,25,'输出3×3');for(let y=0;y<5;y++)for(let x=0;x<5;x++)svg+=box(15+x*27,45+y*27,25,25,String(y*5+x+1));svg+=`<rect x="${14+col*27}" y="${44+row*27}" width="81" height="81" fill="none" stroke="var(--compare)" stroke-width="3"/>`;for(let y=0;y<3;y++)for(let x=0;x<3;x++){const sum=9*(y*5+x+7);svg+=box(212+x*27,65+y*27,25,25,y===row&&x===col?String(sum):'·');}out=`当前窗口起点(行${row},列${col})；输出[${row},${col}]=九个像素相加=${9*(row*5+col+7)}。橙框是输入窗口，输出只显示当前对应格。`;}
 if(kind==='cost'){const totals=[110,70+v];svg=tx(65,55,'旧方案')+tx(65,125,'新方案');for(let i=0;i<2;i++)svg+=`<rect x="110" y="${35+i*70}" width="${totals[i]*1.15}" height="30" fill="var(--series)"/>`+tx(205,85+i*70,totals[i]+' ms');svg+=tx(160,200,'同刻度：条长代表端到端时间');out=`旧总延迟110ms；新总延迟${70+v}ms；加速比=${(110/(70+v)).toFixed(3)}。${v<40?'有净节省':v===40?'恰好抵消':'总时间反而增加'}，不是只看采样60ms。`;}
 if(kind==='environment'||kind==='training'){const names=kind==='environment'?['脚本 .py','解释器 Python','终端输出']:['输入','预测','损失','梯度','更新参数'];svg=names.map((name,i)=>{const y=12+i*40;return box(75,y,170,30,(i===v?'▶ ':'')+name)+(i<names.length-1?line(160,y+30,160,y+40):'');}).join('');out=kind==='environment'?['脚本保存要执行的指令。','所选环境决定解释器和可导入的库。','输出帮助核对预测，并不自动说明掌握。'][v]:['样本及训练标签进入计算。','模型用当前参数给出预测。','损失比较预测与标签。','backward计算梯度，不直接修改参数。','optimizer.step更新参数；下一轮需清空梯度。'][v];}
 if(kind==='matrix'){const a=v===0?[1,2]:[3,4],sum=a[0]+a[1]*2;svg=box(20,45,75,40,`${a[0]} × 1`)+box(125,45,75,40,`${a[1]} × 2`)+tx(110,72,'+')+line(160,90,160,125)+box(90,130,140,40,`和 = ${sum}`);out=`第${v+1}行：[${a}]；输出分量=${a[0]}×1+${a[1]}×2=${sum}。完整输出仍为[5,11]。`;}
 if(kind==='tensor'){svg=tx(78,30,'HWC的通道切片')+tx(242,30,'CHW的通道切片');for(let side=0;side<2;side++)for(let y=0;y<2;y++)for(let x=0;x<3;x++)svg+=box(18+side*164+x*43,55+y*45,38,38,String((y*3+x)*3+v));svg+=tx(160,180,'相同像素，相同数值');out=`HWC形状[2,3,3] → CHW形状[3,2,3]；选中通道${v}。原[0,1,${v}] = 新[${v},0,1] = ${3+v}。`;}
 if(kind==='spread'){svg=line(25,125,295,125)+tx(25,158,'0')+tx(160,158,'2')+tx(295,158,'4');for(const x of [2-v,2,2+v])svg+=dot(25+x*67.5,125);svg+=line(160,55,160,110,'v-other')+tx(160,45,'均值始终为2');out=`输入=[${(2-v).toFixed(1)},2,${(2+v).toFixed(1)}]；总体方差=${(2*v*v/3).toFixed(3)}；标准差=${Math.sqrt(2*v*v/3).toFixed(3)}。重合点表示数值相同。`;}
 if(kind==='gradient'){const xmap=w=>40+(w+1)*65,ymap=l=>185-l*34,w=2-2*v;svg=axis()+path(Array.from({length:81},(_,i)=>{const x=-1+i*.05;return[xmap(x),ymap((x-1)**2)];}))+dot(xmap(2),ymap(1))+`<rect x="${xmap(w)-5}" y="${ymap((w-1)**2)-5}" width="10" height="10" fill="var(--compare)"/>`+tx(170,218,'横轴 w；纵轴 损失L')+tx(230,35,'圆点：起点')+tx(230,56,'方块：更新后');out=`起点w=2，L=1；η=${v.toFixed(2)} → w′=${w.toFixed(2)}，L′=${((w-1)**2).toFixed(3)}。`;}
 if(kind==='noise'){const eps=gaussianNoise(49),clean=eps.map((_,i)=>Math.sin(i/7)),mixed=clean.map((x,i)=>Math.sqrt(v)*x+Math.sqrt(1-v)*eps[i]);svg=line(20,110,300,110)+path(clean.map((x,i)=>[20+i*280/48,110-x*25]),'v-other')+path(mixed.map((x,i)=>[20+i*280/48,110-x*25]))+tx(160,212,'横轴：位置；纵轴：信号幅值')+tx(27,35,'+3')+tx(27,190,'−3');out=`信号系数=${Math.sqrt(v).toFixed(3)}；噪声系数=${Math.sqrt(1-v).toFixed(3)}。标量例：x₀=.8，ε=−.3 → xₜ=${(.8*Math.sqrt(v)-.3*Math.sqrt(1-v)).toFixed(4)}。`;legend=true;}
 if(kind==='schedule'){svg=axis()+path(Array.from({length:11},(_,t)=>[38+t*26,185-150*.8**t]))+dot(38+v*26,185-150*.8**v)+tx(160,215,'横轴：步数t；纵轴：ᾱ')+tx(24,39,'1')+tx(24,188,'0');out=`每步α=0.8；${v}步后的ᾱ=${(.8**v).toFixed(5)}。图中从t=0的1开始。`;}
 if(kind==='ode'){let x=1;const pts=[[38,35]];for(let i=1;i<=v;i++){x*=1-1/v;pts.push([38+i*260/v,185-150*x]);}svg=axis()+path(Array.from({length:51},(_,i)=>[38+i*260/50,185-150*Math.exp(-i/50)]),'v-other')+path(pts)+tx(160,215,'时间t：0 → 1；纵轴：x')+tx(23,39,'1')+tx(23,188,'0');out=`Euler ${v}步，函数评估${v}次；终点=${x.toFixed(5)}，精确值=${Math.exp(-1).toFixed(5)}，绝对误差=${Math.abs(x-Math.exp(-1)).toFixed(5)}。`;legend=true;}
 if(kind==='metric'){svg=axis()+path([[38,155],[298,35]])+dot(38+(v-1)*65,185-v*30)+tx(160,215,'横轴：k=1→5；纵轴：PSNR')+tx(21,39,'50')+tx(21,158,'10');out=`MSE=10⁻${v.toFixed(1)}=${(10**(-v)).toPrecision(3)}；PSNR=${(10*v).toFixed(1)} dB。`;}
 if(kind==='posterior'){const a=v*v,b=.25**2,m=(a*.5+b*.7)/(a+b),variance=a*b/(a+b);svg=line(30,120,290,120)+dot(30,120)+dot(290,120)+tx(60,155,'先验 .5')+tx(260,155,'观测 .7')+`<rect x="${30+(m-.5)*1300-5}" y="105" width="10" height="30" fill="var(--compare)"/>`+tx(160,60,'方块：后验均值');out=`σ=${v.toFixed(2)}；后验均值m=${m.toFixed(4)}；后验方差=${variance.toFixed(5)}。τ=.25不变。`;}
 if(kind==='budget'){const p=[.7,.92,.96],b=[8,16,32],idx=p.findIndex(x=>x>=v),chosen=idx<0?1:idx;svg=axis()+line(38,185-v*145,298,185-v*145,'v-other');for(let i=0;i<3;i++){const x=75+i*88;svg+=`<rect x="${x-18}" y="${185-p[i]*145}" width="36" height="${p[i]*145}" fill="${i===chosen?'var(--series)':'#c6d5c5'}"/>`+tx(x,205,b[i]+'步')+tx(x,185-p[i]*145-9,p[i].toFixed(2));}out=`门槛${v.toFixed(2)}：${idx<0?'没有达标候选，回退默认':'选择成本最低的候选'}${b[chosen]}步，教学成本${[12,21,40][chosen]}ms。虚线是门槛，不是实测风险上界。`;}
 if(kind==='calibration'){const p=v/10;svg=axis()+line(38,50,298,50,'v-other')+`<rect x="125" y="${185-p*150}" width="70" height="${p*150}" fill="var(--series)"/>`+tx(238,40,'预测0.9')+tx(160,208,'实际达标比例')+tx(24,39,'1')+tx(24,188,'0');out=`预测0.90；实际${v}/10=${p.toFixed(2)}；分箱经验差=${Math.abs(.9-p).toFixed(2)}。${p<.9?'这一箱表现为过度自信。':p>.9?'这一箱表现为保守预测。':'这一箱经验比例吻合，但样本很少。'}`;}
 if(kind==='split'){const groups=v===0?[['A1','A2'],['B1','B2'],['C1','C2']]:[['A1','B1'],['A2','C1'],['B2','C2']];svg=groups.map((g,i)=>tx(60+i*100,35,['训练','校准','测试'][i])+g.map((s,j)=>box(20+i*100,55+j*57,80,42,s)).join('')).join('');out=v===0?'每个原场景只进入一个集合，再在集合内部裁剪。':'A、B、C均跨集合出现：测试并非独立场景，存在泄漏风险。';}
 if(kind==='local'){const vals=[.5-v,.5+v,.5-v,.5+v];for(let i=0;i<4;i++){const x=74+(i%2)*90,y=28+Math.floor(i/2)*76,c=Math.round(vals[i]*255);svg+=`<rect x="${x}" y="${y}" width="80" height="48" fill="rgb(${c},${c},${c})"/>`+tx(x+40,y+66,vals[i].toFixed(2));}out=`全局均值始终0.50，局部总体方差=${(v*v).toFixed(4)}。每个灰块代表一个区域的平均亮度。`;}
 if(kind==='nullspace'){svg=box(25,30,270,40,`候选 x̂ = [1, ${v.toFixed(1)}]`)+line(160,70,160,100)+box(25,103,270,40,'A只读取第1个分量')+line(160,143,160,170)+box(25,173,270,35,'观测永远为1');out=`观测残差=(1−1)²=0；相对[1,0]的平方误差=${(v*v).toFixed(2)}。注意这里是两个分量平方和，不是除以2后的MSE。`;}
 if(kind==='risk'){const arr=[.6,v/100,v/60],names=['覆盖率','全体错误','选择后失败'];svg=arr.map((p,i)=>tx(70,40+i*65,names[i])+`<rect x="145" y="22" width="0" height="0"/>`+`<rect x="145" y="${25+i*65}" width="${p*145}" height="22" fill="var(--series)"/>`+tx(220,62+i*65,(p*100).toFixed(1)+'%')).join('');out=`总数100，加速60，失败${v}。覆盖率60%；全体错误比例${v}%；选择后失败率${(v/60*100).toFixed(1)}%。各条以100%为相同满刻度。`;}
 if(kind==='uncertainty'){const se=2/Math.sqrt(v);svg=line(30,115,290,115)+line(160-130*se,98,160-130*se,132)+line(160+130*se,98,160+130*se,132)+line(160-130*se,115,160+130*se,115,'v-line')+dot(160,115)+tx(160,60,'均值 ± 1 SE')+tx(30,165,'−1')+tx(160,165,'0')+tx(290,165,'+1');out=`N=${v}，SD=2，SE=${se.toFixed(3)}。以均值0为中心作示意，条带不表示逐个场景取值。`;}
 return{svg:`<svg viewBox="0 0 320 230" role="img" aria-label="${esc(CONCEPT_VISUALS[kind].title)}"><title>${esc(CONCEPT_VISUALS[kind].title)}</title><desc>${esc(out)}</desc>${svg}</svg>`,out,legend};
}
function attachConceptVisual(l){const kind=l.id==='w1d6'?'convolution':['w3d5','w3d6'].includes(l.id)?'cost':Object.keys(VISUAL_LESSONS).find(k=>VISUAL_LESSONS[k].includes(l.id));if(!kind)return;const d=CONCEPT_VISUALS[kind];const panel=document.createElement('section');panel.className='block concept-visual';panel.id='conceptVisual';panel.dataset.kind=kind;panel.innerHTML=`<span class="pill">看得见的原理 · 教学示例</span><h2>${esc(d.title)}</h2><h3>先用生活直觉理解</h3><p>${esc(d.plain)}</p><h3>再对应到数学</h3><p>${esc(d.meaning)}</p><label for="visualParameter">${esc(d.label)}：<output id="visualValue"></output></label><input id="visualParameter" type="range" min="${d.min}" max="${d.max}" step="${d.step}" value="${d.value}"><figure><div id="visualDrawing"></div><div id="visualLegend" class="v-legend"></div><figcaption id="visualReading" class="v-output" aria-live="polite"></figcaption></figure><details><summary>看懂了吗？${esc(d.ask)}</summary><p>${esc(d.answer)}</p></details><p class="source-meta">边界：${esc(d.limit)} 图形参数用于理解，不计入掌握进度。</p>`;const anchor=$('#learningBridge');if(anchor)anchor.after(panel);else $('.lesson-body').prepend(panel);const draw=()=>{const v=Number($('#visualParameter').value),r=conceptDrawing(kind,v);$('#visualValue').textContent=Number.isInteger(v)?String(v):v.toFixed(2);$('#visualDrawing').innerHTML=r.svg;$('#visualReading').textContent=r.out;$('#visualLegend').innerHTML=r.legend?`<span><i class="v-key"></i>${kind==='noise'?'加噪结果':'Euler近似'}</span><span><i class="v-key other"></i>${kind==='noise'?'原始信号':'精确解'}</span>`:'';};$('#visualParameter').oninput=draw;draw();}
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let course,sources,token,state,revision,active=null,saveTimer,saveQueue=Promise.resolve(),dirty=false,conflict=false;
const lessonState=id=>state.lessons[id]||{};
const passed=id=>Object.values(lessonState(id).scores||{}).filter(Boolean).length===2;
const completed=id=>{const s=lessonState(id);return s.read&&s.practice&&passed(id)&&s.answer?.trim().length>=10;};
const due=id=>completed(id)&&!lessonState(id).reviewed&&lessonState(id).reviewAt<=Date.now();
function toast(text){$('#toast').textContent=text;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',4500);}
async function api(path,data){const request=()=>fetch(path,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json','X-Study-Token':token}:{},body:data?JSON.stringify(data):undefined});let r=await request();if(r.status===403&&data){const session=await fetch('/api/session');if(session.ok){token=(await session.json()).token;r=await request();}}const j=await r.json();if(!r.ok){if(r.status===409&&path==='/api/state')conflict=true;throw Error(j.error||'连接失败');}return j;}
function persist(){clearTimeout(saveTimer);dirty=true;window.studyDrafts?.capture();$('#saveStatus').textContent='保存中…';saveQueue=saveQueue.catch(()=>{}).then(async()=>{if(conflict)throw Error('多窗口版本冲突，已保留草稿；请先导出再核对，不会覆盖另一窗口。');const snapshot=JSON.stringify(state);const res=await api('/api/state',{state:JSON.parse(snapshot),revision});revision=res.revision;dirty=JSON.stringify(state)!==snapshot;$('#saveStatus').textContent=dirty?'保存中…':'已保存到此浏览器';if(!dirty)window.studyDrafts?.acknowledge();else window.studyDrafts?.capture();window.studyDrafts?.status();}).catch(e=>{dirty=true;const retained=window.studyDrafts?.capture();$('#saveStatus').textContent=retained?'未同步 · 草稿已留存':'未保存 · 请导出备份';window.studyDrafts?.status(e.message);toast(e.message);});return saveQueue;}
function update(id,patch,delay=false){const wasComplete=completed(id);state.lessons[id]={...lessonState(id),...patch,updated:Date.now()};if(wasComplete&&!completed(id)){state.lessons[id].reviewed=false;state.lessons[id].reviewAt=0;}if(completed(id)&&!lessonState(id).reviewAt)state.lessons[id].reviewAt=Date.now()+48*3600000;dirty=true;window.studyDrafts?.capture();$('#saveStatus').textContent='等待保存…';clearTimeout(saveTimer);if(delay)saveTimer=setTimeout(persist,350);else persist();}
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
function download(name,obj){const u=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function renderNav(){ $('#weeks').innerHTML=course.weeks.map(w=>`<button class="nav week-button" data-week="${w.id}"><span class="week-num">${w.id===0?'预备':String(w.id).padStart(2,'0')}</span>${esc(w.short)}</button>`).join('');$('#weeks').querySelectorAll('button').forEach(b=>b.onclick=()=>showWeek(Number(b.dataset.week))); }
function page(title,html){$('#breadcrumb').textContent=title;$('#main').innerHTML=html;document.body.classList.remove('menu-open');document.querySelectorAll('.nav').forEach(n=>n.classList.remove('selected'));const week=course.weeks.find(w=>w.title===title||course.lessons.find(l=>l.title===title)?.week===w.id);if(week)document.querySelector(`aside [data-week="${week.id}"]`)?.classList.add('selected');else ({'学习总览':$('#home'),'复习与错题':$('#reviews'),'资料库':$('#library'),'实验记录':$('#results')})[title]?.classList.add('selected');window.scrollTo(0,0);}
function home(){active=null;const done=course.lessons.filter(l=>completed(l.id)).length;const next=course.lessons.find(l=>l.id===state.last&&!completed(l.id))||course.lessons.find(l=>!completed(l.id))||course.lessons[0];const review=course.lessons.filter(l=>due(l.id)).length;page('学习总览',`<div class="eyebrow">YOUR RESEARCH JOURNEY</div><h1>把基础，一点点学扎实。</h1><p class="muted">一条清晰的路径，一个能留下积累的地方。</p><section class="hero"><div><span class="pill">今日建议 · ${esc(next.duration)} 分钟</span><h2>${esc(next.title)}</h2><p>${esc(next.intuition)}</p><button class="primary" id="continue">继续学习 →</button></div><div class="hero-art"><b>理解 → 验证</b><span>先预测，再动手</span><span>先复述，再向前</span></div></section><div class="stats"><div class="stat"><b>${done} / ${course.lessons.length}</b><span>完成首轮验收的短课</span></div><div class="stat"><b>${review}</b><span>到期复习</span></div><div class="stat"><b>8 + 预备</b><span>按掌握程度推进的阶段</span></div></div><div class="section-title"><h2>你的学习地图</h2><small>弱基础建议从预备课开始</small></div><div class="grid">${course.weeks.map(w=>{const ls=course.lessons.filter(l=>l.week===w.id),n=ls.filter(l=>completed(l.id)).length;return `<section class="card"><span class="pill">${w.id===0?'基础衔接':`第 ${w.id} 周`}</span><h3>${esc(w.title)}</h3><p>${esc(w.description)}</p><div class="progress"><span style="width:${n/ls.length*100}%"></span></div><small>${n}/${ls.length} 课完成</small><br><button data-week="${w.id}">进入阶段 →</button></section>`;}).join('')}</div><div class="warning">从零开始时，八周可能需要更长时间。每课完成讲解、练习和自测后，48小时再复述一次。勾选代表你的自评，不能替代独立解决新问题。</div>`);$('#continue').onclick=()=>showLesson(next.id);$$bind('[data-week]',b=>showWeek(Number(b.dataset.week)));}
function $$bind(selector,fn){document.querySelectorAll(selector).forEach(b=>b.onclick=()=>fn(b));}
function showWeek(n){active=null;const w=course.weeks.find(w=>w.id===n);page(w.title,`<div class="eyebrow">${n===0?'FOUNDATION BRIDGE':`WEEK ${String(n).padStart(2,'0')}`}</div><h1>${esc(w.title)}</h1><p class="muted">${esc(w.description)}</p><div class="example">${esc(w.outcome)}</div><div class="lesson-list">${course.lessons.filter(l=>l.week===n).map((l,i)=>`<button class="lesson-row" data-lesson="${l.id}"><div><span>${String(i+1).padStart(2,'0')} · ${esc(l.duration)}分钟</span><br><b>${esc(l.title)}</b></div><span>${completed(l.id)?'✓ 首轮验收完成':lessonState(l.id).read?'学习中':'开始学习 →'}</span></button>`).join('')}</div>${n?`<button id="weekSources">查看本周整合原始讲义</button>`:''}`);$$bind('[data-lesson]',b=>showLesson(b.dataset.lesson));if(n)$('#weekSources').onclick=()=>library(n);}
function showLesson(id){const l=course.lessons.find(l=>l.id===id);if(!l)return home();active=id;state.last=id;persist();const s=lessonState(id),idx=course.lessons.indexOf(l);page(l.title,`<div class="eyebrow">${l.week?'WEEK '+l.week:'基础衔接'} · ${esc(l.duration)} MIN</div><h1>${esc(l.title)}</h1><p class="muted">本课目标：${esc(l.goal)}</p><div class="lesson-layout"><article class="lesson-body"><section class="block"><span class="pill">01 · 先建立直觉</span><h2>这件事为什么值得学？</h2><p>${esc(l.intuition)}</p><h3>一步一步理解</h3>${l.explanation.split('\n\n').map(p=>`<p>${esc(p)}</p>`).join('')}<div class="example"><b>带着数字走一遍</b><br>${esc(l.example)}</div><div class="warning">常见误区：${esc(l.pitfall)}</div><label class="check"><input id="read" type="checkbox" ${s.read?'checked':''}>我已读完，并能用自己的话解释例子。</label></section>${l.lab?labHTML(l.lab):''}<section class="block"><span class="pill">02 · 独立练习</span><h2>先写预测，再看答案</h2><p>${esc(l.exercise)}</p><label for="answer">你的推导、预测与实际结果</label><textarea id="answer" placeholder="写下计算过程、运行结果或自己的解释。至少10个字符，再勾选独立完成。">${esc(s.answer||'')}</textarea><details><summary>查看解题步骤与验收标准</summary><p>${esc(l.solution)}</p></details>${l.code?`<h3>可复制到 Anaconda Prompt 的实践</h3><pre id="code">${esc(l.code)}</pre><button id="copyCode">复制命令</button>`:''}<label class="check"><input id="practice" type="checkbox" ${s.practice?'checked':''}>我已独立完成练习，并核对了过程与结果。</label></section><section class="block"><span class="pill">03 · 检查理解</span><h2>两道题，发现薄弱点</h2>${l.quiz.map((q,i)=>`<div class="quiz"><p><b>${i+1}. ${esc(q.q)}</b></p>${q.options.map((o,j)=>`<label><input type="radio" name="q${i}" value="${j}"> ${esc(o)}</label>`).join('')}<button data-check="${i}">检查答案</button><div class="feedback" id="feedback${i}" role="status">${s.scores&&i in s.scores?(s.scores[i]?'上次回答正确；可以重新作答。':'上次答错，建议回看讲解。'):''}</div></div>`).join('')}</section><section class="block"><h2>留下你的理解</h2><label for="note">笔记、错因与下一次想验证的问题（自动保存）</label><textarea id="note" placeholder="今天我原来以为……现在理解为……">${esc(s.note||'')}</textarea><div id="completion"></div><div class="actions"><button id="reviewDone">我已完成48小时后的独立复述</button><button id="prev" ${idx===0?'disabled':''}>← 上一课</button><button class="primary" id="next">${idx===course.lessons.length-1?'返回总览':'下一课 →'}</button></div></section></article><div class="lesson-side"><div class="card"><h3>本课学习节奏</h3><p>10分钟 · 回忆先修知识<br>20分钟 · 阅读与手算<br>20分钟 · 动手与纠错<br>10分钟 · 闭卷解释</p><hr><h3>先修知识</h3><p>${esc(l.prerequisite)}</p><h3>学完留下什么</h3><p>${esc(l.goal)}</p><button id="openSources">本课来源与延伸</button>${l.week?'<button id="runLab">下载本周本地实验</button><p class="source-meta">每周为一个共用教学实验。各课独立练习各不相同。实验不会自动勾选掌握。</p><pre id="runOutput" hidden></pre>':''}</div></div></div>`);
if(l.snippet){const sn=l.snippet;$('.lesson-body .block').insertAdjacentHTML('afterend',`<section class="block"><span class="pill">动手桥梁 · 完整Python例子</span><h2>${esc(sn.title)}</h2><p>下方脚本包含在可下载的实验包中。先预测输出，再复制命令到 Anaconda Prompt 运行。修改时用编辑器打开对应.py文件，只改一个数，再重新运行。</p><pre>${esc(sn.code)}</pre><h3>运行命令</h3><pre>${esc(sn.command)}</pre><button id="copySnippet">复制练习命令</button><details><summary>核对预期输出</summary><p>${esc(sn.expected)}</p></details></section>`);$('#copySnippet').onclick=async()=>{try{await navigator.clipboard.writeText(sn.command);toast('练习命令已复制');}catch{toast('请选中命令手动复制');}};}
enhanceLearning(l);
if(l.learning_bridge){const b=l.learning_bridge;$('.lesson-body').insertAdjacentHTML('afterbegin',`<section class="block learning-bridge" id="learningBridge"><span class="pill">学习衔接 · 本课承接</span><h2>${esc(b.title)}</h2><p class="bridge-connection">${esc(b.connection)}</p>${b.syntax?`<details><summary>读代码前，先认识这些写法</summary><p>${esc(b.syntax)}</p></details>`:''}<details class="bridge-check"><summary>学完本课再闭卷自检</summary><p>${esc(b.exit_check)}</p><small>先用自己的话回答，再回讲解与练习核对；这不是入门前必须会的内容。</small></details></section>`);}
attachOriginalMaterials(l);
attachConceptVisual(l);
attachSpatialLesson(l);
if(l.week){$('.lesson-side .card').insertAdjacentHTML('beforeend',`<hr><h3>带注释的项目代码</h3><button id="readAnnotatedLab">八周实验：函数与输入输出导读</button>${l.week<=2?'<button id="readAnnotatedToy">二维扩散：中文注释学习版</button>':''}`);$('#readAnnotatedLab').onclick=()=>openSource('p_lab');if($('#readAnnotatedToy'))$('#readAnnotatedToy').onclick=()=>openSource('p_toy');}
for(const name of ['read','practice'])$('#'+name).onchange=e=>{update(id,{[name]:e.target.checked});completion(id);};for(const name of ['note','answer'])$('#'+name).oninput=e=>{update(id,{[name]:e.target.value},true);completion(id);};
$$bind('[data-check]',b=>{const i=Number(b.dataset.check),selected=$(`input[name="q${i}"]:checked`);if(!selected)return toast('请先选择一个答案');const q=l.quiz[i],ok=Number(selected.value)===q.correct;update(id,{scores:{...lessonState(id).scores,[i]:ok}});$('#feedback'+i).className='feedback '+(ok?'ok':'bad');$('#feedback'+i).textContent=(ok?'✓ 回答正确。':'再想一步。')+q.reason;completion(id);});
$('#reviewDone').onclick=()=>{if(!completed(id))return toast('请先完成阅读、练习、两道自测，并写下练习过程。');if(Date.now()<lessonState(id).reviewAt)return toast('首轮验收后48小时再复述；目前可以继续巩固。');update(id,{reviewed:true});completion(id);toast('已记录延迟复述。');};$('#prev').onclick=()=>showLesson(course.lessons[idx-1].id);$('#next').onclick=()=>idx===course.lessons.length-1?home():showLesson(course.lessons[idx+1].id);$('#openSources').onclick=()=>{ $('#modalBody').innerHTML=`<h2>本课来源与延伸</h2><p>本页为重新编写的中文教学讲解，结合原八周材料和下列基础来源；实践数据是教学例子。</p>${l.sources.map(x=>`<p><a href="${esc(x.url)}" target="_blank" rel="noopener">${esc(x.name)}</a></p>`).join('')}<p class="muted">外部原文需要网络。本课正文、练习和答案已保存在本机。</p>`;$('#modal').showModal();};if(l.code)$('#copyCode').onclick=async()=>{try{await navigator.clipboard.writeText(l.code);toast('命令已复制');}catch{toast('自动复制不可用，请选中命令手动复制');}};if(l.lab)attachLab(l.lab);if(l.week)$('#runLab').onclick=()=>runLab(l.week);completion(id);}
function completion(id){if(!$('#completion'))return;const s=lessonState(id);$('#completion').innerHTML=`<p class="muted">${completed(id)?(s.reviewed?'✓ 首轮验收与延迟复述均已记录。':`✓ 首轮验收完成。复习时间：${new Date(s.reviewAt||Date.now()+172800000).toLocaleString('zh-CN')}`):'首轮验收：阅读 + 独立练习 + 两道自测正确 + 写下练习过程。'}</p>`;}
async function runLab(week){const button=$('#runLab'),output=$('#runOutput');button.disabled=true;output.hidden=false;output.textContent='启动本地教学实验…';try{const {job}=await api('/api/lab',{week});while(true){await new Promise(r=>setTimeout(r,800));const j=await api('/api/jobs/'+job);if(active!==state.last)return;output.textContent=j.output;if(j.status!=='running')break;}}catch(e){output.textContent=e.message;}finally{button.disabled=false;}}
function reviews(){active=null;const wrong=course.lessons.filter(l=>Object.values(lessonState(l.id).scores||{}).includes(false)),pending=course.lessons.filter(l=>due(l.id));page('复习与错题',`<div class="eyebrow">RECALL & REPAIR</div><h1>让理解，留得更久。</h1><p class="muted">先闭卷解释，再查看原文。答错记录会在重新答对后移出错题列表。</p><h2>到期复习 · ${pending.length}</h2>${reviewRows(pending,'当前没有到期复习。完成首轮验收后48小时进入这里。')}<h2>需要再想一步 · ${wrong.length}</h2>${reviewRows(wrong,'还没有未纠正的错题。')}<button id="exportNotes">导出学习笔记</button>`);$$bind('[data-lesson]',b=>showLesson(b.dataset.lesson));$('#exportNotes').onclick=()=>download('学习笔记.json',course.lessons.filter(l=>lessonState(l.id).note||lessonState(l.id).answer).map(l=>({title:l.title,...lessonState(l.id)})));}
function reviewRows(ls,empty){return ls.length?`<div class="lesson-list">${ls.map(l=>`<button class="lesson-row" data-lesson="${l.id}">${esc(l.title)}<span>重新学习 →</span></button>`).join('')}</div>`:`<p class="empty">${esc(empty)}</p>`;}
function library(week=null){active=null;const items=sources.filter(s=>week===null||s.week===week);page('资料库',`<div class="eyebrow">REFERENCE LIBRARY</div><h1>需要时，再深入。</h1><p class="muted">旧材料按周整合在这里。日常优先跟随主课程；旧讲义的历史环境与研究设想以新版课程说明为准。</p><div class="library-list">${items.map(s=>`<button data-source="${esc(s.id)}"><b>${esc(s.title)}</b><br><span class="source-meta">第${s.week}周 · ${esc(s.path)}</span></button>`).join('')}</div>`);$$bind('[data-source]',b=>openSource(b.dataset.source));}
function openSource(id){const s=sources.find(s=>s.id===id);if(!s)return toast('该资料不存在，请刷新页面');const related=sources.filter(x=>x.id!==s.id&&x.week===s.week&&x.kind==='讲义');$('#modalBody').innerHTML=`<h2>${esc(s.title)}</h2><p class="source-meta">${esc(s.path)} · 本地完整内容，原文件已迁入工作台</p><p>主课程与当前Anaconda环境说明优先。历史文档里的旧路径/命令可能已过期；原文件按字节保留，当前路径如下。</p><pre>${esc(s.local_path||s.path)}</pre><button id="copyMaterialPath">复制文件路径</button><button id="downloadMaterial">下载当前阅读文本</button><div class="document">${esc(s.body)}</div><h3>同周其他讲义与答案</h3>${related.map(x=>`<button data-related="${esc(x.id)}">${esc(x.title)}</button>`).join('')}`;$('#copyMaterialPath').onclick=()=>copyMaterial(s.local_path||s.path);$('#downloadMaterial').onclick=()=>{const a=document.createElement('a'),u=URL.createObjectURL(new Blob([s.body],{type:'text/plain;charset=utf-8'}));a.href=u;a.download=s.path.split(/[\\/]/).pop()+'.txt';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};$$bind('[data-related]',b=>openSource(b.dataset.related));if(!$('#modal').open)$('#modal').showModal();}

async function copyMaterial(value){try{await navigator.clipboard.writeText(value);toast('路径已复制，可在文件资源管理器地址栏打开');}catch{toast('自动复制不可用，请选中路径复制');}}
function attachOriginalMaterials(l){if(!l.week)return;const selected=(l.supplements||[]).map(id=>sources.find(s=>s.id===id)).filter(Boolean);$('.lesson-body').insertAdjacentHTML('beforeend',`<section class="block" id="originalMaterials"><span class="pill">完整知识补充 · 不再遗漏原计划</span><h2>本周原计划完整讲解与练习</h2><p>短课是学习主线；这里保留原计划完整知识、算例、每日任务和参考答案。按需展开，不必重复完成相同练习。原计划的研究拓展不等于必修，也不代表已完成实验。</p>${selected.map(s=>`<details><summary>${esc(s.title)}</summary><p>历史命令请核对下方当前实践入口。</p><div class="document">${esc(s.body)}</div></details>`).join('')}<div class="actions"><button id="allWeekMaterial">本周全部讲义、模板与附件</button><button id="allMaterialCoverage">八周知识点覆盖索引</button></div><h3>当前实践入口（Anaconda Prompt）</h3><pre>${esc(l.code)}</pre>${l.week===1?`<p>原第一周二维扩散训练项目也已保留，不被线性拟合练习替代。先阅读项目README；以下命令只显示参数帮助，不训练、不覆盖权重。</p><pre>${esc('conda activate yantu-study\npython -X utf8 "'+course.archive_root+'\\补基础第一周\\项目实践\\03_最小二维扩散_PyTorch.py" --help')}</pre>`:''}<p class="source-meta">笔记与验收继续使用本课原有记录；补充阅读不会擅自改变你的学习进度。</p></section>`);$('#allWeekMaterial').onclick=()=>materials(l.week);$('#allMaterialCoverage').onclick=coverage;}
function materials(week=null){active=null;const all=(course.materials||[]).filter(x=>week===null||x.week===week);page('完整材料',`<h1>完整讲义与实践附件</h1><p>学习内容已迁入工作台；讲义、代码、表格可直接阅读，权重等二进制文件通过复制本地路径打开。历史实验与当前实验分开，不把旧输出冒充本次运行。</p><button id="coverageLink">知识点覆盖索引</button><label for="materialSearch">筛选文件名或路径</label><input id="materialSearch" placeholder="例如：二维扩散、参考答案、csv"><div id="materialRows"></div><p class="muted">旧虚拟环境另行原样保留，不列入知识附件，不作为可迁移环境；当前统一使用Anaconda yantu-study。</p>`);const render=()=>{const q=$('#materialSearch').value.trim().toLowerCase(),rows=all.filter(x=>x.path.toLowerCase().includes(q));$('#materialRows').innerHTML=`<p>${rows.length} 个文件</p>`+rows.map(x=>`<section class="card"><b>${esc(x.path)}</b><p class="source-meta">${x.bytes} 字节 · SHA256 ${esc(x.sha256.slice(0,12))}…</p><div class="actions">${x.source_id?`<button data-material-source="${esc(x.source_id)}">阅读内容</button>`:''}<button data-copy-path="${esc(x.local_path)}">复制本地路径</button></div></section>`).join('');$$bind('[data-material-source]',b=>openSource(b.dataset.materialSource));$$bind('[data-copy-path]',b=>copyMaterial(b.dataset.copyPath));};$('#materialSearch').oninput=render;$('#coverageLink').onclick=coverage;render();}
function coverage(){active=null;page('知识点覆盖',`<h1>八周知识点覆盖索引</h1><p>按原文件的全部标题建立索引，正文、练习与附件保留在工作台内。文件哈希证明内容迁存完整，不等于每个主题已经被短课详细讲透。可从下列条目直接阅读完整原文。</p>${Array.from({length:9},(_,w)=>`<details ${w===1?'open':''}><summary>${w?'第'+w+'周':'总计划与工具说明'}</summary>${(course.material_coverage||[]).filter(x=>x.week===w).map(x=>`<section><button data-coverage-source="${esc(x.source_id)}">${esc(x.path)}</button><p class="source-meta">${esc(x.headings.join(' · '))}</p></section>`).join('')}</details>`).join('')}`);$$bind('[data-coverage-source]',b=>openSource(b.dataset.coverageSource));}
const materialsButton=document.createElement('button');materialsButton.id='materials';materialsButton.className='nav';materialsButton.textContent='▤ 完整材料与覆盖索引';materialsButton.onclick=()=>materials();$('#library').after(materialsButton);
async function showResults(){active=null;page('实验记录','<h1>本地实验记录</h1><p>正在读取…</p>');try{const runs=await api('/api/results');page('实验记录',`<div class="eyebrow">LOCAL EXPERIMENTS</div><h1>每次运行，都有据可查。</h1><p class="muted">这里是本地教学实验，不计为论文结果，也不会自动标记课程完成。</p>${runs.length?runs.map(r=>`<section class="card"><h3>${esc(r.id)}</h3><div class="actions">${r.files.map(f=>`<button data-run="${esc(r.id)}" data-file="${esc(f)}">${esc(f)}</button>`).join('')}</div></section>`).join(''):'<p class="empty">还没有实验。进入任一周的课程，点击“下载本周本地实验”。第八周需先运行第六周。</p>'}`);$$bind('[data-run]',async b=>{const url='/api/result/'+b.dataset.run+'/'+b.dataset.file;try{if(/\.(png|svg)$/.test(b.dataset.file))$('#modalBody').innerHTML=`<h2>${esc(b.dataset.file)}</h2><img class="result-image" src="${esc(url)}" alt="教学实验输出">`;else{const r=await api(url);$('#modalBody').innerHTML=`<h2>${esc(r.name)}</h2><pre class="document">${esc(r.text)}</pre>`;}$('#modal').showModal();}catch(e){toast(e.message);}});}catch(e){page('实验记录',`<h1>暂时无法读取实验记录</h1><p>${esc(e.message)}</p>`);}}
const resultsButton=document.createElement('button');resultsButton.id='results';resultsButton.className='nav';resultsButton.textContent='◷ 实验记录';resultsButton.onclick=showResults;$('#library').after(resultsButton);
function search(q){q=q.trim().toLowerCase();if(!q)return home();const ls=course.lessons.filter(l=>JSON.stringify(l).toLowerCase().includes(q)),ss=sources.filter(s=>(s.title+s.body).toLowerCase().includes(q));page('搜索结果',`<h1>搜索结果</h1><p class="muted">“${esc(q)}” · ${ls.length}节课程 · ${ss.length}份原始资料</p>${reviewRows(ls,'没有匹配课程，试试“张量”“梯度”或“概率”。')}<h2>资料库</h2><div class="library-list">${ss.slice(0,50).map(s=>`<button data-source="${s.id}">${esc(s.title)} · 第${s.week}周</button>`).join('')}</div>`);$$bind('[data-lesson]',b=>showLesson(b.dataset.lesson));$$bind('[data-source]',b=>openSource(b.dataset.source));}
function labHTML(kind){const controls={noise:'<label>信号保留量 ᾱ <input id="a" type="range" min="0" max="1" step="0.01" value="0.64"></label>',gradient:'<label>学习率 η <input id="a" type="number" min="0" max="1" step="0.01" value="0.01"></label>',metric:'<label>均方误差 MSE <input id="a" type="number" min="0" step="0.001" value="0.01"></label>',budget:'<label>概率门槛 <input id="a" type="range" min="0.5" max="0.99" step="0.01" value="0.9"></label>'};return `<section class="block"><span class="pill">交互实验 · 合成教学</span><h2>改变一个数，观察结果</h2><div class="lab-controls">${controls[kind]}</div>${kind==='noise'?'<canvas id="canvas" width="600" height="150" aria-label="固定合成信号与噪声叠加图"></canvas>':''}<div id="labResult" class="lab-result" aria-live="polite"></div></section>`;}
function gaussianNoise(count){let seed=731;const uniform=()=>{seed=(1664525*seed+1013904223)>>>0;return (seed+.5)/4294967296;};return Array.from({length:count},()=>Math.sqrt(-2*Math.log(uniform()))*Math.cos(2*Math.PI*uniform()));}
function attachLab(kind){const input=$('#a'),noise=gaussianNoise(600);const calculate=()=>{const a=Number(input.value);if(input.value.trim()===''||!Number.isFinite(a)||a<0||((kind==='noise'||kind==='budget')&&a>1)){$('#labResult').textContent='请输入合法范围内的有限数值';return;}let text='';if(kind==='noise'){const xt=Math.sqrt(a)*.8+Math.sqrt(1-a)*(-.3);text=`ᾱ=${a.toFixed(2)}；信号系数=${Math.sqrt(a).toFixed(3)}；噪声系数=${Math.sqrt(1-a).toFixed(3)}\nx₀=0.8，ε=−0.3 → xₜ=${xt.toFixed(4)}。拖到1时恢复原值；拖到0时只剩噪声。\n曲线使用固定种子的标准高斯伪随机样本；标量手算例子的ε另取−0.3。噪声种子不随滑块改变，纵轴为固定尺度。`;const ctx=$('#canvas').getContext('2d');ctx.clearRect(0,0,600,150);ctx.strokeStyle='#235d49';ctx.beginPath();for(let x=0;x<600;x++){const v=Math.sqrt(a)*Math.sin(x/40)+Math.sqrt(1-a)*noise[x];const y=75-v*16;x?ctx.lineTo(x,y):ctx.moveTo(x,y);}ctx.stroke();}if(kind==='gradient'){const w=2+18*a,b=1+6*a,loss=(3*w+b-10)**2;text=`原损失=9；梯度 dw=−18，db=−6\nw′=${w.toFixed(3)}，b′=${b.toFixed(3)}；新损失=${loss.toFixed(4)}\n试试0、0.01、0.1和0.2。学习率太大可能反而增大损失。`;}if(kind==='metric')text=a===0?'MSE=0：完全一致，PSNR为正无穷；不要把它填成0。':`数据范围 L=1：PSNR=${(-10*Math.log10(a)).toFixed(3)} dB\n数据范围 L=255（MSE数值不变）：PSNR=${(10*Math.log10(255*255/a)).toFixed(3)} dB\n单位变化时误差也要同步缩放，不能只换L来提高分数。`;if(kind==='budget'){const p=[.7,.92,.96],budget=[8,16,32],i=p.findIndex(x=>x>=a);text=`教学概率：[0.70, 0.92, 0.96]；候选预算：[8,16,32]\n门槛=${a.toFixed(2)} → ${i<0?'回退到经过验证的默认16步（教学设定）':`选择${budget[i]}步`}\n这些是假设概率，不是实验结果。门槛0.95不构成5%错误率保证。`;}$('#labResult').textContent=text;};input.oninput=calculate;calculate();}

function enhanceLearning(l){
 const prerequisites={0:[],1:['b3','b4','b7'],2:['b5','w1d4'],3:['b7','w2d5'],4:['b5','w1d3'],5:['b6','w4d1'],6:['b6','w5d6'],7:['w4d6','w6d2'],8:['w6d6','w7d5']};
 const ids=l.prerequisite_ids||(l.week===0?(l.day>1?['b'+(l.day-1)]:[]):prerequisites[l.week]);
 const sidebar=$('.lesson-side .card');sidebar.insertAdjacentHTML('beforeend',`<hr><h3>需要补哪一课？</h3>${ids.length?ids.map(id=>`<button class="prerequisite" data-jump="${id}">${esc(course.lessons.find(x=>x.id===id).title)}</button>`).join(''):'<p>这是起点，无需提前学其他课程。</p>'}`);$$bind('[data-jump]',b=>showLesson(b.dataset.jump));
 const answer=$('#answer');answer.insertAdjacentHTML('beforebegin',`<details class="hint"><summary>卡住了？先看一条提示</summary><p>${esc(l.pitfall)}</p><details><summary>再给一点提示</summary><p>先列出已知量、要计算或解释的量，再参考本课“带着数字走一遍”的步骤。只改变练习要求改变的条件，写清单位或形状。</p></details></details>`);
 const index=course.lessons.indexOf(l);if(index>0){const prev=course.lessons[index-1];$('.lesson-body').insertAdjacentHTML('afterbegin',`<details><summary>课前回忆：${esc(prev.title)}</summary><p>先不翻讲解，用自己的话回答：${esc(prev.quiz[0].q)}</p><details><summary>核对解释</summary><p>${esc(prev.quiz[0].reason)}</p><button id="backPrerequisite">返回这节课</button></details></details>`);$('#backPrerequisite').onclick=()=>showLesson(prev.id);}
 const kinds={b4:'dot',b5:'mean',b6:'risk',b7:'gradient',b8:'update',w1d3:'shape',w1d4:'gradient',w1d6:'conv',w2d1:'noise',w2d2:'schedule',w2d4:'noise',w3d1:'euler',w3d2:'nfe',w3d5:'speed',w4d4:'psnr',w5d2:'posterior',w6d2:'label',w6d6:'budget',w7d5:'risk',w8d2:'se'};
 if(!kinds[l.id])return;
 $('#answer').closest('section').insertAdjacentHTML('beforeend','<div class="transfer"><h3>换一组数字，自己算</h3><p id="transferPrompt"></p><label for="transferAnswer">数值答案（可用小数或分数）</label><input id="transferAnswer" inputmode="decimal" autocomplete="off"><div class="actions"><button id="checkTransfer">核对计算</button><button id="newTransfer">换一道</button></div><p id="transferFeedback" role="status"></p><details><summary>看计算提示</summary><p id="transferHint"></p></details><p class="source-meta">这是补充练习，不替代本课验收；答案不会自动写成你的学习笔记。记录推导到上方练习框。</p></div>');
 let task,sequence=0;
 function make(){const n=2+(sequence++%5);const makers={dot:()=>[`[${n},2]与[3,4]的点积是多少？`,3*n+8,`${n}×3+2×4`],mean:()=>[`[${n},${n+2},${n+4}]的均值是多少？`,n+2,'先求和，再除以3。'],risk:()=>[`有${n*10}张加速图，其中${n}张不达标。选择后失败率是多少？用百分数的数值填写，如10%填写10。`,10,`${n}/(${n*10})×100`],gradient:()=>[`L=(w×${n}-10)²，在w=2时，dL/dw是多少？`,2*(2*n-10)*n,`2×(2×${n}-10)×${n}`],update:()=>[`参数w=2，梯度=-${n}，学习率0.1。更新后的w是多少？`,2+.1*n,`w新=2-0.1×(-${n})`],shape:()=>[`形状[${n},3,4,5]有多少元素？`,n*60,`${n}×3×4×5`],conv:()=>[`输入高${n*8}，卷积核3，padding0，stride1，dilation1，输出高度是多少？`,n*8-2,`${n*8}-3+1`],noise:()=>[`x₀=${n/10}，ε=-0.3，ᾱ=0.64。xₜ是多少？`,.8*n/10-.18,'先开平方：a=.8，s=.6，再算a×x₀+s×ε。'],schedule:()=>[`每步α=.8，经过${n}步后累计ᾱ是多少？`,.8**n,`0.8的${n}次方，不是相加。`],euler:()=>[`dx/dt=-x，x(0)=1，在[0,1]上Euler做${n}步，终点是多少？`,(1-1/n)**n,`每步乘(1-1/${n})，共${n}次。`],nfe:()=>[`Heun做${n}步，每步两次评估，总NFE是多少？`,2*n,`${n}×2`],speed:()=>[`原端到端100ms，新采样${n*10}ms，决策5ms，其他5ms，新总延迟是多少ms？`,n*10+10,'把所有在线部分相加。'],psnr:()=>[`动态范围L=1，MSE=10的负${n}次方。PSNR是多少dB？`,10*n,'PSNR=-10 log10(MSE)。'],posterior:()=>[`先验均值.5，先验与噪声标准差均为.25，观测y=${n/10}，后验均值是多少？`,(.5+n/10)/2,'两种方差相等，因此是先验均值与观测的平均。'],label:()=>[`默认PSNR=${n+25}，容差.2。满足相对PSNR条件的最低分数是多少？`,n+24.8,'默认分数减容差。'],budget:()=>[`10张图，${n}张用8步，其余用16步。平均步数是多少？`,(n*8+(10-n)*16)/10,'总步数除以10。'],se:()=>[`独立场景N=${n*n}，标准差SD=2，均值标准误SE是多少？`,2/n,'SE=SD/√N。']};task=makers[kinds[l.id]]();$('#transferPrompt').textContent=task[0];$('#transferHint').textContent=task[2];$('#transferAnswer').value='';$('#transferFeedback').textContent='先手算；允许四舍五入到小数点后三位。';}
 $('#newTransfer').onclick=make;$('#checkTransfer').onclick=()=>{const raw=$('#transferAnswer').value.trim();const m=raw.match(/^([+-]?(?:\d+(?:\.\d*)?|\.\d+))(?:\s*\/\s*([+-]?(?:\d+(?:\.\d*)?|\.\d+)))?$/);const value=m?Number(m[1])/(m[2]===undefined?1:Number(m[2])):NaN;const out=$('#transferFeedback');if(!Number.isFinite(value)){out.textContent='请输入有限数值或分数，例如0.25或1/4；先不要加单位。';return;}const ok=Math.abs(value-task[1])<=.00051;out.className=ok?'ok':'bad';out.textContent=ok?'✓ 数值吻合。再说明为什么这样算，然后换一题。':'数值还不吻合。检查分母、平方根或更新符号；展开计算提示后再试。';};make();
}
// Coordinate transforms keep the teaching quantities independent of camera angle.
const SPATIAL_LESSONS={tensor:['w1d3','w1d7'],loss:['b7','b8','w1d4','w1d5'],diffusion:['w2d1','w2d3','w2d6'],convolution:['w1d6']};
function spatialProject(point,yaw=35,elevation=25){const a=yaw*Math.PI/180,e=elevation*Math.PI/180;const x=point[0]*Math.cos(a)-point[1]*Math.sin(a),y=point[0]*Math.sin(a)+point[1]*Math.cos(a);return{x:160+32*x,y:174+32*(y*Math.sin(e)-point[2]*Math.cos(e)),depth:y*Math.cos(e)+point[2]*Math.sin(e)};}
function spatialLoss(rate,steps){let w=1.8,b=1.2;const values=[];for(let i=0;i<=steps;i++){values.push({w,b,loss:(w-1)**2+2*(b+.5)**2});const gw=2*(w-1),gb=4*(b+.5);w-=rate*gw;b-=rate*gb;}return values;}
function spatialVoxel(x,y,z,s){const v=[[x-s,y-s,z-s],[x+s,y-s,z-s],[x+s,y+s,z-s],[x-s,y+s,z-s],[x-s,y-s,z+s],[x+s,y-s,z+s],[x+s,y+s,z+s],[x-s,y+s,z+s]];return [[0,1,2,3],[4,5,6,7],[0,1,5,4],[1,2,6,5],[2,3,7,6],[3,0,4,7]].map(face=>face.map(i=>v[i]));}
function spatialDensity(x,y,alpha){const variance=alpha*.35**2+1-alpha,a=Math.sqrt(alpha);return [[-1.5,-1],[1.5,-1],[-1.5,1],[1.5,1]].reduce((p,c)=>p+Math.exp(-((x-a*c[0])**2+(y-a*c[1])**2)/(2*variance))/(8*Math.PI*variance),0);}
function spatialDraw(kind,p){
 const project=v=>spatialProject(v,p.yaw,p.elevation),txt=(x,y,t)=>`<text x="${x}" y="${y}" text-anchor="middle">${esc(t)}</text>`;
 const polygon=(vertices,fill,stroke='#7d9a85',opacity=1)=>{const v=vertices.map(project);return{depth:v.reduce((s,q)=>s+q.depth,0)/v.length,html:`<polygon points="${v.map(q=>q.x.toFixed(2)+','+q.y.toFixed(2)).join(' ')}" fill="${fill}" stroke="${stroke}" stroke-width=".7" opacity="${opacity}"/>`};};
 const edges=(a,b,color='#85968a')=>{a=project(a);b=project(b);return `<line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" stroke="${color}" stroke-width="1.4"/>`;};
 const marker=(point,color,r=4)=>{const q=project(point);return `<circle cx="${q.x}" cy="${q.y}" r="${r}" fill="${color}" stroke="#fff" stroke-width="1.5"/>`;};
 let graphic='',message='',rows=[],question='',answer='';
 if(kind==='tensor'){
  const index=p.index,h=Math.floor(index/9),w=Math.floor(index%9/3),c=index%3;
  if(p.mode==='3d'){
   const faces=[];for(let ch=0;ch<3;ch++)for(let row=0;row<2;row++)for(let col=0;col<3;col++){const x=col-1,y=row-.5,z=ch*.8,selected=row===h&&col===w&&ch===c,s=.32;const color=selected?'#a45321':['#d1e2d0','#bed4ca','#a7c5bf'][ch];for(const vertices of spatialVoxel(x,y,z,s))faces.push(polygon(vertices,color));}
   graphic=faces.sort((a,b)=>a.depth-b.depth).map(f=>f.html).join('')+edges([-1.7,-1,0],[1.7,-1,0])+edges([-1.7,-1,0],[-1.7,1,0])+edges([-1.7,-1,0],[-1.7,-1,2.1])+txt(245,225,'W：列')+txt(70,225,'H：行')+txt(95,66,'C：通道');
  }else{for(let ch=0;ch<3;ch++){graphic+=txt(54+ch*105,40,'通道 '+ch);for(let row=0;row<2;row++)for(let col=0;col<3;col++){const value=(row*3+col)*3+ch,selected=value===index;graphic+=`<rect x="${12+ch*105+col*28}" y="${65+row*40}" width="25" height="32" fill="${selected?'#a45321':'#d7e5d5'}"/>`+txt(24.5+ch*105+col*28,88+row*40,value);}}}
  rows=[['HWC索引',`[${h},${w},${c}]`],['CHW索引',`[${c},${h},${w}]`],['同一像素值',index],['HWC形状→CHW形状','[2,3,3] → [3,2,3]']];message=`橙色块是当前像素 ${index}。旋转只改变观察角度；切换二维/三维不会改变数值或索引对应。每个小块表示一个标量，三个通道不是三张独立样本。`;question='把通道换到最前面，是把像素数值重新排序成任意形状吗？';answer='不是。permute同时改变轴的顺序与索引解释；原像素通过对应的新索引仍取到相同值。';
 }
 if(kind==='loss'){
  const trace=spatialLoss(p.rate,p.steps),last=trace.at(-1),faces=[];
  if(p.mode==='3d'){for(let i=0;i<16;i++)for(let j=0;j<16;j++){const x=-2+i*.25,y=-2+j*.25,points=[[x,y],[x+.25,y],[x+.25,y+.25],[x,y+.25]],height=(x-1)**2+2*(y+.5)**2;faces.push(polygon(points.map(([w,b])=>[w,b,((w-1)**2+2*(b+.5)**2)*.12]),`hsl(140 24% ${78-Math.min(25,height)}%)`));}graphic=faces.sort((a,b)=>a.depth-b.depth).map(f=>f.html).join('');}
  else{const fx=w=>45+(w+2)*57,fy=b=>220-(b+2)*44;for(let k=1;k<=5;k++)graphic+=`<ellipse cx="${fx(1)}" cy="${fy(-.5)}" rx="${Math.sqrt(k)*57}" ry="${Math.sqrt(k/2)*44}" fill="none" stroke="#a8bdad"/>`;graphic+=txt(160,270,'横轴 w；纵轴 b；椭圆是等损失线');}
  const visible=trace.filter(q=>q.w>=-2&&q.w<=2&&q.b>=-2&&q.b<=2);for(let i=0;i<visible.length;i++){const q=visible[i],point=[q.w,q.b,q.loss*.12+.03];if(p.mode==='3d'){graphic+=marker(point,i===visible.length-1?'#a45321':'#235d49');if(i)graphic+=edges([visible[i-1].w,visible[i-1].b,visible[i-1].loss*.12+.03],point,'#a45321');}else{const x=45+(q.w+2)*57,y=220-(q.b+2)*44;graphic+=`<circle cx="${x}" cy="${y}" r="4" fill="#a45321"/>`;if(i)graphic+=`<line x1="${45+(visible[i-1].w+2)*57}" y1="${220-(visible[i-1].b+2)*44}" x2="${x}" y2="${y}" stroke="#a45321" stroke-width="2"/>`;}}
  if(p.mode==='3d')graphic+=txt(160,260,'地面轴：w与b；高度：0.12L');
  rows=[['当前更新次数',p.steps],['权重 w',last.w.toFixed(4)],['偏置 b',last.b.toFixed(4)],['当前损失 L',last.loss.toFixed(5)],['起点损失',trace[0].loss.toFixed(5)]];message=`L=(w−1)²+2(b+0.5)²；梯度=(2(w−1),4(b+0.5))。最小值在(1,−0.5)。${visible.length<trace.length?'有迭代点超出绘图域[−2,2]，图中省略这些点，表中仍显示真实数值。':'橙色轨迹表示按同一个学习率连续更新。'} 相机旋转不会改变优化结果。`;question='为什么学习率对w合适，却可能让b方向振荡？';answer='b方向曲率更大，梯度变化更快。此例b误差每次乘(1−4η)，w误差乘(1−2η)，两个方向的稳定范围不同。';
 }
 if(kind==='diffusion'){
  const alpha=p.alpha,a=Math.sqrt(alpha),variance=alpha*.35**2+1-alpha;
  if(p.mode==='3d'){const faces=[];for(let i=0;i<22;i++)for(let j=0;j<22;j++){const x=-3.5+i*7/22,y=-3.5+j*7/22,step=7/22;const vertices=[[x,y],[x+step,y],[x+step,y+step],[x,y+step]].map(([x,y])=>[x,y,4*spatialDensity(x,y,alpha)]);const density=spatialDensity(x,y,alpha);faces.push(polygon(vertices,`hsl(140 28% ${83-Math.min(30,density*70)}%)`));}graphic=faces.sort((a,b)=>a.depth-b.depth).map(f=>f.html).join('')+txt(160,265,'平面：x₁、x₂；高度：4×密度p');}
  else{const noise=gaussianNoise(384);for(let i=0;i<96;i++){const center=[[-1.5,-1],[1.5,-1],[-1.5,1],[1.5,1]][i%4],x0=center[0]+.35*noise[i*2],y0=center[1]+.35*noise[i*2+1],x=a*x0+Math.sqrt(1-alpha)*noise[192+i*2],y=a*y0+Math.sqrt(1-alpha)*noise[193+i*2];if(Math.abs(x)<=3.5&&Math.abs(y)<=3.5)graphic+=`<circle cx="${160+x*38}" cy="${145-y*34}" r="2.5" fill="#235d49" opacity=".7"/>`;}graphic+=`<line x1="27" y1="145" x2="293" y2="145" stroke="#a6b5a8"/><line x1="160" y1="25" x2="160" y2="264" stroke="#a6b5a8"/>`+txt(278,170,'x₁')+txt(178,30,'x₂');}
  rows=[['信号系数 √ᾱ',a.toFixed(4)],['噪声系数 √(1−ᾱ)',Math.sqrt(1-alpha).toFixed(4)],['每个簇的条件方差',variance.toFixed(4)],['一个原簇中心→当前中心',`(1.5,1) → (${(1.5*a).toFixed(3)},${a.toFixed(3)})`]];message='二维点是固定种子的96个样本，三维面是四个等权高斯簇加噪后的解析概率密度。两种视图描述同一分布，有限样本不会逐点等于密度。ᾱ=0时各簇合成标准二维高斯；ᾱ=1时保留原四簇。';question='这个点云变化是否说明去噪网络已经学会恢复？';answer='这里只演示前向加噪。学习逆过程还需噪声预测器、训练目标和走到采样终点的恢复过程。';
 }
 if(kind==='convolution'){
  const channels=[[1,2,3,4],[5,6,7,8]],parts=[10,26*p.weight];
  if(p.mode==='3d'){const faces=[];for(let c=0;c<2;c++){const z=c*1.2;faces.push(polygon([[-.9,-.9,z],[.9,-.9,z],[.9,.9,z],[-.9,.9,z]],c?'#bdd4c7':'#dfe9d7','#709681',.8));for(let k=0;k<4;k++){const q=project([k%2-.5,Math.floor(k/2)-.5,z]);graphic+=txt(q.x,q.y+5,channels[c][k]);}}graphic=faces.sort((a,b)=>a.depth-b.depth).map(f=>f.html).join('')+graphic+edges([.9,0,0],[2.3,0,.6])+edges([.9,0,1.2],[2.3,0,.6])+marker([2.3,0,.6],'#a45321',6)+txt(160,250,'两层通道 → 一个输出标量');}
  else{graphic=txt(80,35,'通道0，核权重1')+txt(238,35,'通道1，核权重k');for(let c=0;c<2;c++)for(let j=0;j<4;j++)graphic+=`<rect x="${33+c*160+j%2*45}" y="${65+Math.floor(j/2)*45}" width="40" height="40" fill="#d3e3d0"/>`+txt(53+c*160+j%2*45,91+Math.floor(j/2)*45,channels[c][j]);graphic+=txt(160,215,`10 + 26 × ${p.weight.toFixed(1)} = ${(10+26*p.weight).toFixed(1)}`);}
  rows=[['输入形状 C×H×W','2×2×2'],['通道0贡献',parts[0]],['通道1贡献',parts[1].toFixed(2)],['一个输出通道的值',(parts[0]+parts[1]).toFixed(2)],['输出形状','1×1×1']];message='一个输出通道的卷积核跨越全部输入通道。这里是2×2核、无补边、无偏置；先在各通道求加权和，再把通道贡献相加。三个输入通道并不必然产生三个输出通道。';question='如果有两个输出通道，需要怎样改变卷积核？';answer='需要两组独立权重，每组都覆盖全部输入通道，各组计算一个输出通道。';
 }
 return {svg:`<svg viewBox="0 0 320 280" role="img" aria-label="${esc(kind)}教学视图"><title>二维与可旋转三维教学视图</title><desc>${esc(message)}</desc>${graphic}</svg>`,message,rows,question,answer};
}
function attachSpatialLesson(l){
 const kind=Object.keys(SPATIAL_LESSONS).find(k=>SPATIAL_LESSONS[k].includes(l.id));if(!kind)return;
 const titles={tensor:'把张量展开，再从空间看同一像素',loss:'沿二维等高线走，再看三维损失曲面',diffusion:'二维点云与三维概率密度怎样对应',convolution:'卷积为什么要跨输入通道相加'};
 const intro={tensor:'先在二维展开图选一个像素，再切三维看它所属的行、列和通道。只旋转观察角度，数值保持不变。',loss:'把两个参数当作地面位置，损失当作高度。先用小学习率走几步，再比较大步长的振荡或越界。',diffusion:'先滑动ᾱ观察四簇如何混合，再切换三维密度理解“样本很多的地方概率密度较高”。',convolution:'先把每个通道算成一个贡献，再看两层输入如何共同形成一个输出。试着把第二个通道的权重改成零或负数。'};
 const parameter={tensor:[['index','像素编号（HWC展开）',0,17,1,4]],loss:[['rate','学习率 η',0,.55,.05,.1],['steps','更新次数',0,8,1,4]],diffusion:[['alpha','信号保留量 ᾱ',0,1,.02,.64]],convolution:[['weight','第二通道的核权重 k',-1,1,.1,1]]}[kind];
 const panel=document.createElement('section');panel.id='spatialLab';panel.className='block spatial-lab';panel.dataset.kind=kind;
 panel.innerHTML=`<span class="pill">空间理解实验室</span><h2>${titles[kind]}</h2><p>${intro[kind]}</p><div class="spatial-tabs" role="group" aria-label="切换观察方式"><button id="sp2d" aria-pressed="true">二维展开</button><button id="sp3d" aria-pressed="false">三维观察</button><button id="spReset">重置实验</button></div><div class="spatial-controls">${parameter.map(([id,title,min,max,step,value])=>`<label for="sp_${id}">${title}：<output id="spValue_${id}">${value}</output><input id="sp_${id}" type="range" min="${min}" max="${max}" step="${step}" value="${value}"></label>`).join('')}<div id="spCamera" hidden><label for="spYaw">左右旋转：<output id="spYawValue">35°</output><input id="spYaw" type="range" min="-180" max="180" step="5" value="35"></label><label for="spElevation">俯视角：<output id="spElevationValue">25°</output><input id="spElevation" type="range" min="10" max="70" step="5" value="25"></label></div></div><figure><div id="spDrawing"></div><figcaption class="spatial-note">二维和三维使用相同参数。改变相机只改变图形投影，下面的计算结果保持一致。</figcaption></figure><div id="spMessage" class="sp-output" aria-live="polite"></div><table class="spatial-table"><caption>图形对应的数值</caption><thead><tr><th scope="col">量</th><th scope="col">当前值</th></tr></thead><tbody id="spRows"></tbody></table><details><summary id="spQuestion"></summary><p id="spAnswer"></p></details><p class="spatial-note">本图为可计算的教学示例；三维高度缩放在图中标明。图形不自动勾选课程掌握。理解后在本课练习框记录一条预测与实际差异。</p>`;
 ($('#conceptVisual')||$('#learningBridge')).after(panel);let mode='2d';
 const redraw=()=>{const p={mode,yaw:Number($('#spYaw').value),elevation:Number($('#spElevation').value)};for(const [id] of parameter){p[id]=Number($('#sp_'+id).value);$('#spValue_'+id).textContent=p[id];}const r=spatialDraw(kind,p);$('#spDrawing').innerHTML=r.svg;$('#spMessage').textContent=r.message;$('#spRows').innerHTML=r.rows.map(([name,value])=>`<tr><th scope="row">${esc(name)}</th><td>${esc(value)}</td></tr>`).join('');$('#spQuestion').textContent=r.question;$('#spAnswer').textContent=r.answer;$('#spCamera').hidden=mode==='2d';$('#sp2d').setAttribute('aria-pressed',String(mode==='2d'));$('#sp3d').setAttribute('aria-pressed',String(mode==='3d'));$('#spYawValue').textContent=p.yaw+'°';$('#spElevationValue').textContent=p.elevation+'°';};
 for(const input of panel.querySelectorAll('input'))input.oninput=redraw;$('#sp2d').onclick=()=>{mode='2d';redraw();};$('#sp3d').onclick=()=>{mode='3d';redraw();};$('#spReset').onclick=()=>{mode='2d';for(const [id,,,,,value] of parameter)$('#sp_'+id).value=value;$('#spYaw').value=35;$('#spElevation').value=25;redraw();};redraw();
}
const STUDY_TERMS=[
 ['张量 Tensor','带有形状的数值容器。图像批次常用BCHW：样本数、通道数、高、宽。','w1d3'],['广播 Broadcasting','维度从右侧对齐，某维相等或一方为1时可扩展计算。','w1d3'],['梯度 Gradient','损失对各参数的局部变化率；负梯度是局部降低损失的方向。','w1d4'],['自动求导 Autograd','沿计算图按链式法则求梯度；计算梯度与更新参数是两个步骤。','w1d4'],['卷积 Convolution','对局部窗口做加权汇总，核覆盖全部输入通道；输出通道数由核组数决定。','w1d6'],['累计信号量 ᾱ','多个α的乘积。前向加噪中信号系数为√ᾱ，噪声系数为√(1−ᾱ)。','w2d2'],['噪声预测 ε-prediction','训练网络预测加入样本的噪声。标签来自训练时的加噪，部署时使用预测。','w2d3'],['参数化 Parameterization','网络输出代表噪声、干净样本或v；采样器必须使用对应转换公式。','w2d4'],['完整采样预算','一条走到干净终点的时间表；减少步数不等于中途截断长时间表。','w2d5'],['常微分方程 ODE','描述状态随连续时间变化的斜率，采样器用有限更新近似连续过程。','w3d1'],['函数评估次数 NFE','模型实际被调用的次数；每步调用两次的算法不能只按步数比较。','w3d2'],['端到端延迟','从输入到输出的约定时间，包括在线特征、决策、采样与回退等开销。','w3d5'],['均方误差 MSE','配对元素的差平方后平均；单位、范围和对齐影响解释。','w4d4'],['峰值信噪比 PSNR','10 log₁₀(L²/MSE)，L为约定动态范围；零误差需特殊处理。','w4d4'],['场景泄漏','同源场景的裁剪或退化版本跨集合出现，使测试不再独立。','w4d6'],['后验 Posterior','给定观测后的未知清晰目标分布，由先验与观测生成机制共同决定。','w5d1'],['多标签监督','每档预算分别判断是否达标，多个预算可同时达标。','w6d2'],['概率校准 Calibration','检查预测概率与经验成功频率是否一致；还需检查最终选择策略。','w6d4'],['回退 Fallback','当前低成本候选缺乏把握时，使用事先验证的默认方案。','w6d5'],['零空间 Null space','观测算子完全看不见的变化；观测残差小不保证这些变化正确。','w7d3'],['选择后失败率','实际采用加速方案的样本中，质量不达标者的比例。','w7d5'],['标准误 SE','均值估计的波动量级；独立样本假设下常为SD/√N。','w8d2'],['自助重采样 Bootstrap','从独立场景有放回抽样，估计统计量波动；重复种子不能代替独立场景。','w8d3']
];
function studyGuide(){active=null;page('原专项知识地图与术语',`<h1>回看原八周专项知识</h1><p>这里保留原专项阶段，不是十六周主线的周次。入门建议按“学习路线”推进；卡住时从术语跳回讲解和可视化，阶段验收在学完后进行。</p><div class="study-map">${course.weeks.map(w=>`<section class="card"><div class="stage-number">${w.id===0?'基础衔接':'原专项第'+w.id+'阶段'}</div><h2>${esc(w.title)}</h2><p>${esc(w.description)}</p><p>学完后验收：${esc(w.outcome)}</p><button data-guide-week="${w.id}">进入本阶段</button></section>`).join('')}</div><h2>术语随用随查</h2><p>定义是入门解释，点击进入对应课程，查看例子、图形和边界。</p><div class="glossary-grid">${STUDY_TERMS.map(([term,meaning,id])=>`<section class="card"><h3>${esc(term)}</h3><p>${esc(meaning)}</p><button data-guide-lesson="${id}">查看课程</button></section>`).join('')}</div>`);$$bind('[data-guide-week]',b=>showWeek(Number(b.dataset.guideWeek)));$$bind('[data-guide-lesson]',b=>showLesson(b.dataset.guideLesson));}
const navigationRoutes={home,showWeek,showLesson,reviews,library,materials,coverage,showResults,search,studyGuide};
home=trackedPage('home',home);showWeek=trackedPage('showWeek',showWeek);showLesson=trackedPage('showLesson',showLesson);reviews=trackedPage('reviews',reviews);library=trackedPage('library',library);materials=trackedPage('materials',materials);coverage=trackedPage('coverage',coverage);showResults=trackedPage('showResults',showResults);search=trackedPage('search',search);
studyGuide=trackedPage('studyGuide',studyGuide);
const guideButton=document.createElement('button');guideButton.id='studyGuide';guideButton.className='nav';guideButton.textContent='◇ 知识地图与术语';guideButton.onclick=()=>studyGuide();$('#reviews').after(guideButton);
$('#results').onclick=()=>showResults();
const backButton=document.createElement('button');backButton.id='goBack';backButton.type='button';backButton.textContent='← 返回';backButton.setAttribute('aria-label','返回上一页，无历史时返回学习总览');backButton.onclick=returnToPrevious;document.body.append(backButton);
const modalBackButton=document.createElement('button');modalBackButton.type='button';modalBackButton.textContent='← 返回课程页面';modalBackButton.onclick=()=>$('#modal').close();$('#closeModal').before(modalBackButton);
async function init(){try{[course,sources]=await Promise.all([fetch('./course.json').then(r=>r.json()),fetch('./sources.json').then(r=>r.json())]);token=(await api('/api/session')).token;({state,revision}=await api('/api/state'));renderNav();home();$('#saveStatus').textContent='已连接 · 本机保存';window.studyUIReady?.();}catch(e){$('#main').innerHTML=`<h1>暂时无法读取课程</h1><p>${esc(e.message)}</p><p>请重新双击启动程序，检查终端中的错误信息后刷新页面。</p>`;}}
$('#home').onclick=home;$('#reviews').onclick=reviews;$('#library').onclick=()=>library();$('#menu').onclick=()=>document.body.classList.toggle('menu-open');$('#closeModal').onclick=()=>$('#modal').close();$('#search').oninput=e=>search(e.target.value);$('#export').onclick=()=>download('研途学习备份_'+new Date().toISOString().slice(0,10)+'.json',{app:'dacim-study-v1',exported:new Date().toISOString(),state});$('#import').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>2_000_000)throw Error('备份超过2MB');const data=JSON.parse(await f.text());if(data.app!=='dacim-study-v1'||data.state?.schema!==1)throw Error('不是本程序的学习备份');if(!confirm('导入将替换当前学习进度。建议先导出当前备份。确认导入？'))return;await persist();const result=await api('/api/state',{state:data.state,revision});revision=result.revision;state=data.state;dirty=false;home();toast('备份已导入并保存到本机');}catch(err){toast('导入失败：'+err.message);}finally{e.target.value='';}};
